- hosts: LAB
  gather_facts: false
  connection: local


  tasks:
  

  - name: Cisco show cmd
    ios_command:
      commands:
        - show ip route 
    register: showiproute

  - debug: var=showiproute.stdout_lines


  
