- hosts: LAB
  gather_facts: false
  vars_files:
    - ./vars/ios_config_vars.yaml

  tasks:
  - name: Show running config
    ios_command:
     commands:
       - show snmp user | i User
       - show running-config
    register: showrun

  - debug: var=showrun.stdout_lines


  - name: get ntp servers
    set_fact: get_ntp_servers_{{ inventory_hostname }}="{{showrun.stdout[1] | regex_findall('^ntp server [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}', multiline=True) }}"

  - name: get dns servers
    set_fact: get_dns_servers_{{ inventory_hostname }}="{{showrun.stdout[1] | regex_findall('^ip name-server [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}', multiline=True) }}"

  - debug: var=get_ntp_servers_{{inventory_hostname}}
  - debug: var=get_ntp_servers
  - debug: var=get_dns_servers

  - name: Write facts to text 
    template:
      src: ./templates/ios_show_template.j2
      dest: ./reports/show_output_file
    run_once: true
