- hosts: LAB
  gather_facts: false
  vars_files:
    - ./vars/ios_config_vars.yaml

  tasks:
  - name: Show running config
    ios_command:
     commands:
       - show snmp user | i User
       - show running-config
    register: showrun

  - debug: var=showrun.stdout_lines


  - name: get local users
    set_fact: get_local_users="{{showrun.stdout[1] | regex_findall('username (\S+)', multiline=True) }}"

  - name: get ntp servers
    set_fact: get_ntp_servers="{{showrun.stdout[1] | regex_findall('^ntp server [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}', multiline=True) }}"

  - name: get dns servers
    set_fact: get_dns_servers="{{showrun.stdout[1] | regex_findall('^ip name-server [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}', multiline=True) }}"

  - name: get snmp view
    set_fact: get_snmp_view="{{showrun.stdout[1] | regex_findall('snmp-server view.*', multiline=True) }}"
  
  - name: get snmp groups
    set_fact: get_snmp_groups="{{showrun.stdout[1] | regex_findall('snmp-server group.*', multiline=True) }}"

  - name: get snmp user
    set_fact: get_snmp_users="{{showrun.stdout[0] | regex_findall('^User name. (\S+)', multiline=True) }}"


#  - debug: var=get_ntp_servers
#  - debug: var=get_dns_servers

  - name: Write facts to text 
    template:
      src: ./templates/ios_show_template.j2
      dest: ./reports/report_output_{{inventory_hostname}}

