- hosts: LAB
  gather_facts: false
  connection: network_cli
  vars_files: 
    - ./vars/ios_vars_list.yaml 




  tasks:
  
  - name: Cisco config loop
    ios_config:
      lines: 
        - " {{ item }}"
    with_items: " {{ config_list }}"