Group1:
  hosts:
    R1:
      ansible_host: 10.0.1.1
  vars: 
    Site: site11
    Branch: branch11
    NTP_server: 10.0.0.11

Group2:
  hosts:
    R2:
      ansible_host: 10.0.1.2
  vars: 
    Site: site22
    Branch: branch22
    NTP_server: 10.0.0.22

Group3:
  hosts:
    R3:
      ansible_host: 10.0.1.3
  vars: 
    Site: site33
    Branch: branch33
    NTP_server: 10.0.0.33

Group4:
  hosts:
    R4:
      ansible_host: 10.0.1.4
    R5: 
      ansible_host: 10.0.1.5
    R6:
      ansible_host: 10.0.1.6
  vars: 
    Site: site44
    Branch: branch44
    NTP_server: 10.0.0.44


LAB:
  children:
    Group1:
    Group2:
    Group3:
    Group4:
  vars:
    ansible_network_os: ios